#title in header
title: "Nikita Mikhailovskiy"

#main info
#owner
#owner: "I am Nikita Mikhailovskiy"
email: nmihaylovskiy@gmail.com
info: "Welcome to my tiny blog 😎"
desc: "Software & Electrical Engineer, Student. Loves coffee, coding, and robots."

#menu
menu:
  Projects: /projects
  About: /about

#index/main page max show posts (in number)
max_post: 15

# Colors use hex color without #
# Theme color
tcolor: 0bb1bd

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
# usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/CityAplons
linkedin: https://www.linkedin.com/in/nikita-mikhailovskiy/
instagram: https://www.instagram.com/mcbeer194/
stackoverflow: https://stackoverflow.com/story/nikita.mikhailovskiy

# Misc
nanobar: /js/nanobar.min.js
switch_light: 🔲
switch_dark: ⬛

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
